/*
Copyright (C) 2025 SubRouter

This program is free software: you can redistribute it and/or modify
it under the terms of the GNU Affero General Public License as
published by the Free Software Foundation, either version 3 of the
License, or (at your option) any later version.

This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
GNU Affero General Public License for more details.

You should have received a copy of the GNU Affero General Public License
along with this program. If not, see <https://www.gnu.org/licenses/>.

For commercial licensing, please contact support@subrouter.ai
*/

const translatedLocales = ['en', 'ja', 'fr', 'ru', 'vi', 'zh-TW', 'tr'];

const translationRows = `

48.45.22.14 或 proxy.example.com	48.45.22.14 or proxy.example.com	48.45.22.14 または proxy.example.com	48.45.22.14 ou proxy.example.com	48.45.22.14 или proxy.example.com	48.45.22.14 hoặc proxy.example.com	48.45.22.14 或 proxy.example.com	48.45.22.14 veya proxy.example.com
7 天收益成熟期	7-day earnings maturity period	7 日間の収益確定期間	Délai de maturation des gains de 7 jours	7-дневный срок созревания дохода	Thời gian chờ ghi nhận doanh thu 7 ngày	7 天收益成熟期	7 günlük kazanç olgunlaşma süresi
AWS Session Token（可选）	AWS Session Token (optional)	AWS Session Token（任意）	AWS Session Token (facultatif)	AWS Session Token (необязательно)	AWS Session Token (không bắt buộc)	AWS Session Token（可選）	AWS Session Token (isteğe bağlı)
OAuth 启动失败	Failed to start OAuth	OAuth を開始できませんでした	Échec du démarrage OAuth	Не удалось запустить OAuth	Không thể bắt đầu OAuth	OAuth 啟動失敗	OAuth başlatılamadı
OAuth 账号	OAuth accounts	OAuth アカウント	Comptes OAuth	Аккаунты OAuth	Tài khoản OAuth	OAuth 帳號	OAuth hesapları
OAuth 账号导入并通过连通性测试后直接启用，不需要人工审核。平台自动识别套餐，未知套餐会进入隔离状态等待确认。	OAuth accounts are enabled after import and connectivity testing without manual review. The platform detects the plan automatically; unknown plans are quarantined for confirmation.	OAuth アカウントはインポートと接続テストの完了後、手動審査なしで有効になります。プランは自動判定され、不明なプランは確認待ちとして隔離されます。	Les comptes OAuth sont activés après l'importation et le test de connectivité, sans contrôle manuel. La plateforme détecte automatiquement l'offre ; les offres inconnues sont mises en quarantaine pour confirmation.	Аккаунты OAuth включаются после импорта и проверки соединения без ручной проверки. Тариф определяется автоматически; неизвестные тарифы помещаются в карантин до подтверждения.	Tài khoản OAuth được bật sau khi nhập và kiểm tra kết nối mà không cần duyệt thủ công. Nền tảng tự nhận diện gói; gói chưa xác định sẽ được cách ly để xác nhận.	OAuth 帳號匯入並通過連線測試後會直接啟用，無需人工審核。平台會自動識別套餐，未知套餐會進入隔離狀態等待確認。	OAuth hesapları içe aktarıldıktan ve bağlantı testi geçildikten sonra manuel inceleme olmadan etkinleştirilir. Platform planı otomatik olarak algılar; bilinmeyen planlar onay beklemek üzere karantinaya alınır.
Service Account JSON 格式无效	Invalid Service Account JSON	Service Account JSON の形式が無効です	Format JSON du compte de service non valide	Недопустимый формат Service Account JSON	Định dạng Service Account JSON không hợp lệ	Service Account JSON 格式無效	Service Account JSON biçimi geçersiz
{{platform}} 账号类型	{{platform}} account type	{{platform}} アカウント種別	Type de compte {{platform}}	Тип аккаунта {{platform}}	Loại tài khoản {{platform}}	{{platform}} 帳號類型	{{platform}} hesap türü
下载格式示例	Download format example	形式例をダウンロード	Télécharger un exemple de format	Скачать пример формата	Tải ví dụ định dạng	下載格式範例	Biçim örneğini indir
专属代理	Dedicated proxy	専用プロキシ	Proxy dédié	Выделенный прокси	Proxy riêng	專屬代理	Özel proxy
不健康	Unhealthy	異常	Non sain	Неисправен	Không khỏe mạnh	不健康	Sağlıksız
为提高账号存活率，建议购买并使用静态住宅 IP。	For better account stability, use a static residential IP.	アカウントの安定性を高めるため、固定住宅 IP の使用を推奨します。	Pour améliorer la stabilité du compte, utilisez une IP résidentielle statique.	Для повышения стабильности аккаунта рекомендуется статический резидентский IP.	Để tăng độ ổn định của tài khoản, nên dùng IP dân cư tĩnh.	為提高帳號存活率，建議購買並使用靜態住宅 IP。	Hesap kararlılığını artırmak için sabit bir konut IP’si kullanmanızı öneririz.
代理仅绑定当前托管账号，提交前会测试连通性；支持公网 IP 或域名。	The proxy is bound only to this hosted account and tested before submission. Public IPs and domain names are supported.	プロキシは現在のホストアカウントだけに紐づき、送信前に接続テストを行います。グローバル IP またはドメイン名に対応しています。	Le proxy est lié uniquement à ce compte hébergé et testé avant l'envoi. Les IP publiques et noms de domaine sont pris en charge.	Прокси привязывается только к этому аккаунту и проверяется перед отправкой. Поддерживаются публичные IP и домены.	Proxy chỉ gắn với tài khoản lưu trữ hiện tại và được kiểm tra trước khi gửi. Hỗ trợ IP công khai và tên miền.	代理僅綁定目前的托管帳號，提交前會測試連線；支援公網 IP 或網域名稱。	Proxy yalnızca bu barındırılan hesaba bağlanır ve gönderilmeden önce bağlantısı test edilir. Genel IP’ler ve alan adları desteklenir.
你可以随时暂停、恢复或移除账号。暂停后不再分配新请求，历史收益与审计记录继续保留。	You can pause, resume, or remove an account at any time. Paused accounts receive no new requests, while earnings and audit history remain available.	アカウントはいつでも一時停止、再開、削除できます。一時停止中は新規リクエストが割り当てられず、過去の収益と監査記録は保持されます。	Vous pouvez suspendre, reprendre ou supprimer un compte à tout moment. Un compte suspendu ne reçoit plus de requêtes, mais les gains et journaux d'audit sont conservés.	Аккаунт можно приостановить, возобновить или удалить в любое время. После паузы новые запросы не назначаются, а история доходов и аудита сохраняется.	Bạn có thể tạm dừng, tiếp tục hoặc xóa tài khoản bất cứ lúc nào. Tài khoản tạm dừng không nhận yêu cầu mới, còn doanh thu và lịch sử kiểm tra vẫn được giữ lại.	你可以隨時暫停、恢復或移除帳號。暫停後不再分配新請求，歷史收益與稽核記錄會繼續保留。	Bir hesabı istediğiniz zaman duraklatabilir, yeniden etkinleştirebilir veya kaldırabilirsiniz. Duraklatılan hesaplara yeni istek atanmaz; kazanç ve denetim geçmişi korunur.
你应确保账号来源合法并有权托管。供应商凭证仅发送至 Sub2，Subrouter 用户接口不会返回凭证或内部账号标识。	You must have the legal right to host the account. Provider credentials are sent only to Sub2; Subrouter user APIs never return credentials or internal account identifiers.	アカウントの入手元が適法で、ホストする権限があることを確認してください。プロバイダー認証情報は Sub2 のみに送信され、Subrouter のユーザー API から認証情報や内部アカウント ID が返されることはありません。	Vous devez disposer du droit légal d'héberger le compte. Les identifiants du fournisseur sont envoyés uniquement à Sub2 ; les API utilisateur Subrouter ne renvoient jamais les identifiants ni les ID internes des comptes.	Вы должны иметь законное право на размещение аккаунта. Учетные данные провайдера отправляются только в Sub2; пользовательские API Subrouter не возвращают учетные данные или внутренние идентификаторы.	Bạn phải có quyền hợp pháp để lưu trữ tài khoản. Thông tin xác thực nhà cung cấp chỉ được gửi tới Sub2; API người dùng Subrouter không trả về thông tin xác thực hoặc mã tài khoản nội bộ.	你應確保帳號來源合法並有權托管。供應商憑證僅傳送至 Sub2，Subrouter 使用者介面不會回傳憑證或內部帳號識別碼。	Hesabı barındırmak için yasal hakkınız olduğundan emin olmalısınız. Sağlayıcı kimlik bilgileri yalnızca Sub2’ye gönderilir; SubRouter kullanıcı API’leri bu bilgileri veya dahili hesap tanımlayıcılarını asla döndürmez.
健康	Healthy	正常	Sain	Исправен	Khỏe mạnh	健康	Sağlıklı
健康状态	Health status	稼働状態	État de santé	Состояние	Trạng thái hoạt động	健康狀態	Sağlık durumu
公网 IP / 域名	Public IP / domain	グローバル IP / ドメイン	IP publique / domaine	Публичный IP / домен	IP công khai / tên miền	公網 IP / 網域名稱	Genel IP / alan adı
共享市场	Shared Marketplace	共有マーケット	Marché partagé	Общий маркетплейс	Chợ dùng chung	共享市場	Paylaşılan pazar yeri
配置中	Provisioning	設定中	Configuration en cours	Настройка	Đang cấu hình	設定中	Yapılandırılıyor
分成比例	Revenue share	収益分配率	Part des revenus	Доля дохода	Tỷ lệ chia sẻ doanh thu	分成比例	Gelir paylaşımı
删除账号	Delete account	アカウントを削除	Supprimer le compte	Удалить аккаунт	Xóa tài khoản	刪除帳號	Hesabı sil
加密货币钱包	Crypto wallet	暗号資産ウォレット	Portefeuille crypto	Криптокошелек	Ví tiền mã hóa	加密貨幣錢包	Kripto para cüzdanı
协议	Protocol	プロトコル	Protocole	Протокол	Giao thức	協定	Protokol
即时上线与套餐检测	Immediate activation and plan detection	即時有効化とプラン判定	Activation immédiate et détection de l'offre	Мгновенное включение и определение тарифа	Kích hoạt ngay và nhận diện gói	即時上線與套餐檢測	Anında etkinleştirme ve plan algılama
即时转为站内可消费余额，不计入充值金额。	Convert instantly to spendable platform balance. This does not count as a top-up.	プラットフォーム内で利用できる残高に即時変換します。チャージ額には加算されません。	Conversion immédiate en solde utilisable sur la plateforme, sans être comptée comme recharge.	Мгновенно переводится в доступный баланс платформы и не считается пополнением.	Chuyển ngay thành số dư có thể dùng trên nền tảng và không tính là nạp tiền.	即時轉為站內可消費餘額，不計入儲值金額。	Anında platformda kullanılabilir bakiyeye dönüştürülür. Bu tutar bakiye yükleme olarak sayılmaz.
厂商与套餐	Provider and plan	プロバイダーとプラン	Fournisseur et offre	Провайдер и тариф	Nhà cung cấp và gói	廠商與套餐	Sağlayıcı ve plan
可用收益	Available earnings	利用可能な収益	Gains disponibles	Доступный доход	Doanh thu khả dụng	可用收益	Kullanılabilir kazançlar
可转入平台余额或申请提现	Transfer to platform balance or request a payout	プラットフォーム残高への振替または出金申請が可能です	Transférables vers le solde de la plateforme ou disponibles au retrait	Можно перевести на баланс платформы или вывести	Có thể chuyển vào số dư nền tảng hoặc yêu cầu rút tiền	可轉入平台餘額或申請提領	Platform bakiyesine aktarılabilir veya para çekme talebi oluşturabilirsiniz
可选，填写实名或付款说明	Optional: enter the recipient name or payment instructions	任意：受取人名または支払い説明を入力	Facultatif : indiquez le nom du bénéficiaire ou les instructions de paiement	Необязательно: укажите имя получателя или комментарий к платежу	Không bắt buộc: điền tên người nhận hoặc ghi chú thanh toán	可選，填寫實名或付款說明	İsteğe bağlı: alıcı adını veya ödeme talimatlarını girin
合规与凭证保护	Compliance and credential protection	コンプライアンスと認証情報保護	Conformité et protection des identifiants	Соответствие требованиям и защита учетных данных	Tuân thủ và bảo vệ thông tin xác thực	合規與憑證保護	Uyumluluk ve kimlik bilgisi koruması
启用账号	Enable account	アカウントを有効化	Activer le compte	Включить аккаунт	Bật tài khoản	啟用帳號	Hesabı etkinleştir
在浏览器中完成授权	Complete authorization in your browser	ブラウザーで認証を完了	Terminer l'autorisation dans le navigateur	Завершите авторизацию в браузере	Hoàn tất ủy quyền trong trình duyệt	在瀏覽器中完成授權	Yetkilendirmeyi tarayıcınızda tamamlayın
在线容量	Online capacity	オンライン容量	Capacité en ligne	Активная емкость	Dung lượng trực tuyến	線上容量	Çevrimiçi kapasite
复制授权链接	Copy authorization link	認証リンクをコピー	Copier le lien d'autorisation	Копировать ссылку авторизации	Sao chép liên kết ủy quyền	複製授權連結	Yetkilendirme bağlantısını kopyala
套餐费率	Plan rates	プラン料率	Tarifs des offres	Тарифы планов	Mức phí theo gói	套餐費率	Plan ücretleri
完整回调链接，例如	Full callback URL, for example	完全なコールバック URL の例	URL de rappel complète, par exemple	Полный callback URL, например	URL callback đầy đủ, ví dụ	完整回呼連結，例如	Tam geri çağrı URL’si, örneğin
密码（可选）	Password (optional)	パスワード（任意）	Mot de passe (facultatif)	Пароль (необязательно)	Mật khẩu (không bắt buộc)	密碼（可選）	Parola (isteğe bağlı)
导入失败	Import failed	インポートに失敗しました	Échec de l'importation	Ошибка импорта	Nhập thất bại	匯入失敗	İçe aktarma başarısız oldu
导入结果	Import results	インポート結果	Résultats de l'importation	Результаты импорта	Kết quả nhập	匯入結果	İçe aktarma sonuçları
导入账号归属当前用户，系统会逐个测试代理和账号，通过后启用。支持内联 proxy、proxy_url，或顶层 proxies 配合账号 proxy_id；API Key 和其他认证类型会跳过。	Imported accounts belong to the current user. Each proxy and account is tested before activation. Inline proxy and proxy_url are supported, as are top-level proxies referenced by proxy_id. API keys and other authentication types are skipped.	インポートしたアカウントは現在のユーザーに属します。プロキシとアカウントを個別にテストし、合格後に有効化します。インラインの proxy、proxy_url、およびトップレベルの proxies と proxy_id の組み合わせに対応し、API キーなど他の認証方式はスキップします。	Les comptes importés appartiennent à l'utilisateur actuel. Chaque proxy et compte est testé avant activation. Les champs proxy et proxy_url intégrés sont pris en charge, ainsi que les proxies de premier niveau référencés par proxy_id. Les clés API et autres méthodes d'authentification sont ignorées.	Импортированные аккаунты принадлежат текущему пользователю. Каждый прокси и аккаунт проверяется перед включением. Поддерживаются встроенные proxy и proxy_url, а также верхнеуровневые proxies со ссылкой proxy_id. API-ключи и другие типы авторизации пропускаются.	Tài khoản đã nhập thuộc người dùng hiện tại. Hệ thống kiểm tra từng proxy và tài khoản trước khi bật. Hỗ trợ proxy, proxy_url nội tuyến hoặc proxies cấp cao nhất kết hợp proxy_id; API Key và kiểu xác thực khác sẽ bị bỏ qua.	匯入的帳號歸屬目前使用者，系統會逐一測試代理與帳號，通過後啟用。支援內嵌 proxy、proxy_url，或頂層 proxies 搭配帳號 proxy_id；API Key 與其他驗證類型會略過。	İçe aktarılan hesaplar mevcut kullanıcıya aittir. Sistem her proxy’yi ve hesabı tek tek test eder, başarılı olanları etkinleştirir. Satır içi proxy ve proxy_url ile proxy_id üzerinden başvurulan üst düzey proxies desteklenir; API Key’ler ve diğer kimlik doğrulama türleri atlanır.
将跳过	Will skip	スキップ	Ignorés	Будет пропущено	Sẽ bỏ qua	將略過	Atlanacak
已保存：{{details}}	Saved: {{details}}	保存済み：{{details}}	Enregistré : {{details}}	Сохранено: {{details}}	Đã lưu: {{details}}	已儲存：{{details}}	Kaydedildi: {{details}}
已删除	Deleted	削除済み	Supprimé	Удален	Đã xóa	已刪除	Silindi
已启用账号 / 全部账号	Enabled accounts / all accounts	有効なアカウント / 全アカウント	Comptes activés / tous les comptes	Включенные аккаунты / все аккаунты	Tài khoản đã bật / tất cả tài khoản	已啟用帳號 / 全部帳號	Etkin hesaplar / tüm hesaplar
已导入 {{succeeded}} 个，跳过 {{skipped}} 个，失败 {{failed}} 个	Imported {{succeeded}}, skipped {{skipped}}, failed {{failed}}	{{succeeded}} 件をインポート、{{skipped}} 件をスキップ、{{failed}} 件が失敗	{{succeeded}} importés, {{skipped}} ignorés, {{failed}} en échec	Импортировано: {{succeeded}}, пропущено: {{skipped}}, ошибок: {{failed}}	Đã nhập {{succeeded}}, bỏ qua {{skipped}}, thất bại {{failed}}	已匯入 {{succeeded}} 個，略過 {{skipped}} 個，失敗 {{failed}} 個	{{succeeded}} içe aktarıldı, {{skipped}} atlandı, {{failed}} başarısız oldu
已批准	Approved	承認済み	Approuvé	Одобрено	Đã phê duyệt	已核准	Onaylandı
已撤销	Reversed	取り消し済み	Annulé	Отменено	Đã hoàn tác	已撤銷	Geri alındı
已支付	Paid	支払い済み	Payé	Выплачено	Đã thanh toán	已支付	Ödendi
已绑定代理	Proxy bound	プロキシ設定済み	Proxy lié	Прокси привязан	Đã gắn proxy	已綁定代理	Proxy bağlandı
已自动识别代理信息	Proxy details detected	プロキシ情報を自動判定しました	Informations du proxy détectées	Данные прокси распознаны	Đã tự nhận diện thông tin proxy	已自動識別代理資訊	Proxy bilgileri otomatik algılandı
已转入平台余额	Transferred to platform balance	プラットフォーム残高に振り替えました	Transféré vers le solde de la plateforme	Переведено на баланс платформы	Đã chuyển vào số dư nền tảng	已轉入平台餘額	Platform bakiyesine aktarıldı
已释放	Released	確定済み	Libéré	Доступно	Đã phát hành	已釋放	Serbest bırakıldı
平台比例	Platform share	プラットフォーム分	Part de la plateforme	Доля платформы	Tỷ lệ nền tảng	平台比例	Platform payı
开始导入	Start import	インポートを開始	Démarrer l'importation	Начать импорт	Bắt đầu nhập	開始匯入	İçe aktarmayı başlat
待释放	Pending release	確定待ち	En attente de libération	Ожидает разблокировки	Chờ phát hành	待釋放	Serbest bırakılmayı bekliyor
待释放收益	Pending earnings	確定待ち収益	Gains en attente	Ожидающий доход	Doanh thu chờ phát hành	待釋放收益	Serbest bırakılmayı bekleyen kazançlar
成功 {{succeeded}} 个，跳过 {{skipped}} 个，失败 {{failed}} 个。	{{succeeded}} succeeded, {{skipped}} skipped, {{failed}} failed.	成功 {{succeeded}} 件、スキップ {{skipped}} 件、失敗 {{failed}} 件。	{{succeeded}} réussis, {{skipped}} ignorés, {{failed}} en échec.	Успешно: {{succeeded}}, пропущено: {{skipped}}, ошибок: {{failed}}.	Thành công {{succeeded}}, bỏ qua {{skipped}}, thất bại {{failed}}.	成功 {{succeeded}} 個，略過 {{skipped}} 個，失敗 {{failed}} 個。	{{succeeded}} başarılı, {{skipped}} atlandı, {{failed}} başarısız oldu.
我的托管账号	My hosted accounts	ホスト中のアカウント	Mes comptes hébergés	Мои размещенные аккаунты	Tài khoản tôi lưu trữ	我的托管帳號	Barındırdığım hesaplar
或仅输入 code 参数值	or enter only the code parameter	または code パラメーターの値だけを入力	ou saisissez uniquement le paramètre code	или введите только значение параметра code	hoặc chỉ nhập giá trị tham số code	或僅輸入 code 參數值	veya yalnızca code parametresinin değerini girin
打开授权链接	Open authorization link	認証リンクを開く	Ouvrir le lien d'autorisation	Открыть ссылку авторизации	Mở liên kết ủy quyền	開啟授權連結	Yetkilendirme bağlantısını aç
托管规则与分成	Hosting rules and revenue share	ホスティング規則と収益分配	Règles d'hébergement et partage des revenus	Правила размещения и распределение дохода	Quy tắc lưu trữ và chia sẻ doanh thu	托管規則與分成	Barındırma kuralları ve gelir paylaşımı
托管账号	Hosted Accounts	ホストアカウント	Comptes hébergés	Размещенные аккаунты	Tài khoản lưu trữ	托管帳號	Barındırılan hesaplar
批量导入	Batch Import	一括インポート	Importation groupée	Пакетный импорт	Nhập hàng loạt	批次匯入	Toplu içe aktarma
批量导入失败	Batch import failed	一括インポートに失敗しました	Échec de l'importation groupée	Ошибка пакетного импорта	Nhập hàng loạt thất bại	批次匯入失敗	Toplu içe aktarma başarısız oldu
批量导入托管账号	Batch import hosted accounts	ホストアカウントを一括インポート	Importer des comptes hébergés en lot	Пакетный импорт размещенных аккаунтов	Nhập hàng loạt tài khoản lưu trữ	批次匯入托管帳號	Barındırılan hesapları toplu içe aktar
折扣决定共享套餐的调用价格，贡献者分成按具体套餐独立配置；所有比例均可透明查看。	The discount determines the shared plan's usage price. Contributor revenue shares are configured per plan, and every rate is visible.	割引率によって共有プランの利用価格が決まり、貢献者の収益分配率はプランごとに設定されます。すべての比率を確認できます。	La remise détermine le prix d'utilisation de l'offre partagée. La part des contributeurs est configurée par offre et tous les taux sont visibles.	Скидка определяет стоимость использования общего тарифа. Доля участника настраивается отдельно для каждого тарифа, все ставки прозрачны.	Mức giảm giá quyết định giá sử dụng gói dùng chung. Tỷ lệ chia sẻ cho người đóng góp được cấu hình riêng theo từng gói và đều được hiển thị minh bạch.	折扣決定共享套餐的呼叫價格，貢獻者分成會依具體套餐獨立設定；所有比例均可透明查看。	İndirim, paylaşılan planın çağrı fiyatını belirler. Katkıda bulunan gelir payları her plan için ayrı yapılandırılır; tüm oranlar şeffaf biçimde görüntülenebilir.
按真实用量计费	Billing by actual usage	実使用量に基づく計算	Facturation selon l'utilisation réelle	Расчет по фактическому использованию	Tính phí theo mức sử dụng thực tế	按真實用量計費	Gerçek kullanıma göre faturalandırılır
接入失败	Connection failed	接続に失敗しました	Échec de la connexion	Не удалось подключить	Kết nối thất bại	接入失敗	Bağlantı başarısız oldu
提交提现申请	Submit payout request	出金申請を送信	Envoyer la demande de retrait	Отправить заявку на вывод	Gửi yêu cầu rút tiền	提交提領申請	Para çekme talebi gönder
提交收款方式后由管理员审核并线下打款。	After you submit payment details, an administrator reviews the request and pays you offline.	受取方法を送信すると、管理者が審査しオフラインで支払います。	Après l'envoi des coordonnées de paiement, un administrateur examine la demande et effectue le paiement hors ligne.	После отправки платежных реквизитов администратор проверит заявку и выполнит выплату вне платформы.	Sau khi gửi phương thức nhận tiền, quản trị viên sẽ xét duyệt và thanh toán ngoại tuyến.	提交收款方式後由管理員審核並線下付款。	Ödeme yöntemi gönderildikten sonra bir yönetici tarafından incelenir ve ödeme çevrim dışı yapılır.
提现申请失败	Payout request failed	出金申請に失敗しました	Échec de la demande de retrait	Не удалось создать заявку на вывод	Yêu cầu rút tiền thất bại	提領申請失敗	Para çekme talebi başarısız oldu
支持 URL、主机:端口:用户名:密码等常见格式	Supports URLs and common host:port:username:password formats	URL や host:port:username:password 形式に対応	Prend en charge les URL et les formats hôte:port:utilisateur:mot de passe	Поддерживаются URL и форматы host:port:username:password	Hỗ trợ URL và định dạng máy_chủ:cổng:tên_đăng_nhập:mật_khẩu	支援 URL、主機:連接埠:使用者名稱:密碼等常見格式	URL ile ana makine:bağlantı noktası:kullanıcı adı:parola gibi yaygın biçimler desteklenir
支持 sub2api 账号备份格式，一次最多导入 200 个 OAuth 账号；每个账号必须绑定专属代理。	Supports sub2api account backups and imports up to 200 OAuth accounts at once. Every account must have a dedicated proxy.	sub2api アカウントバックアップ形式に対応し、一度に最大 200 件の OAuth アカウントをインポートできます。各アカウントには専用プロキシが必要です。	Prend en charge les sauvegardes de comptes sub2api et jusqu'à 200 comptes OAuth par importation. Chaque compte doit avoir un proxy dédié.	Поддерживаются резервные копии sub2api и импорт до 200 OAuth-аккаунтов за раз. Для каждого аккаунта нужен выделенный прокси.	Hỗ trợ bản sao lưu tài khoản sub2api và nhập tối đa 200 tài khoản OAuth mỗi lần. Mỗi tài khoản phải có proxy riêng.	支援 sub2api 帳號備份格式，一次最多匯入 200 個 OAuth 帳號；每個帳號都必須綁定專屬代理。	sub2api hesap yedekleme biçimi desteklenir; tek seferde en fazla 200 OAuth hesabı içe aktarılabilir. Her hesabın özel bir proxy’ye bağlı olması gerekir.
支持完整 callback URL、查询字符串或裸 code。	Supports a full callback URL, query string, or raw code.	完全な callback URL、クエリ文字列、または code のみを入力できます。	Accepte une URL de rappel complète, une chaîne de requête ou le code brut.	Поддерживается полный callback URL, строка запроса или чистый code.	Hỗ trợ URL callback đầy đủ, chuỗi truy vấn hoặc code thuần.	支援完整 callback URL、查詢字串或單獨的 code。	Tam geri çağrı URL’si, sorgu dizesi veya yalın code desteklenir.
收款账号	Payment account	受取アカウント	Compte de paiement	Платежный аккаунт	Tài khoản nhận tiền	收款帳號	Ödeme hesabı
收益基于该账号实际承担请求产生的成功计费金额计算。同一用量记录只结算一次，失败请求不会产生收益。	Earnings are calculated from successfully billed requests handled by the account. Each usage record is settled once, and failed requests earn nothing.	収益は、そのアカウントが処理した成功課金リクエストに基づいて計算されます。同じ利用記録は一度だけ精算され、失敗したリクエストには収益が発生しません。	Les gains sont calculés sur les requêtes facturées avec succès et traitées par le compte. Chaque utilisation n'est réglée qu'une fois et les requêtes échouées ne génèrent aucun gain.	Доход рассчитывается по успешно тарифицированным запросам, обработанным аккаунтом. Каждая запись использования оплачивается один раз, неудачные запросы дохода не приносят.	Doanh thu được tính từ các yêu cầu thành công do tài khoản xử lý. Mỗi bản ghi sử dụng chỉ được quyết toán một lần và yêu cầu thất bại không tạo doanh thu.	收益依該帳號實際承擔請求所產生的成功計費金額計算。同一筆用量記錄只結算一次，失敗請求不會產生收益。	Kazançlar, bu hesabın gerçekten işlediği isteklerin başarıyla faturalandırılan tutarına göre hesaplanır. Her kullanım kaydı yalnızca bir kez ödenir; başarısız istekler kazanç oluşturmaz.
收益明细	Earnings Details	収益明細	Détails des gains	Детализация дохода	Chi tiết doanh thu	收益明細	Kazanç ayrıntıları
文件中没有可导入的 OAuth 账号	No importable OAuth accounts found in the file	ファイル内にインポート可能な OAuth アカウントがありません	Aucun compte OAuth importable dans le fichier	В файле нет OAuth-аккаунтов для импорта	Không tìm thấy tài khoản OAuth có thể nhập trong tệp	檔案中沒有可匯入的 OAuth 帳號	Dosyada içe aktarılabilir OAuth hesabı bulunamadı
文件账号	Accounts in file	ファイル内アカウント	Comptes dans le fichier	Аккаунты в файле	Tài khoản trong tệp	檔案帳號	Dosyadaki hesaplar
新收益先进入待释放状态，7 天后自动变为可用；异常、退款或冲正用量会按原记录撤销。	New earnings remain pending for 7 days before becoming available. Abnormal, refunded, or reversed usage is reversed against the original record.	新しい収益は 7 日間確定待ちとなった後、自動的に利用可能になります。異常、返金、訂正された利用分は元の記録に基づいて取り消されます。	Les nouveaux gains restent en attente pendant 7 jours avant d'être disponibles. Les utilisations anormales, remboursées ou annulées sont contrepassées sur l'enregistrement d'origine.	Новый доход ожидает разблокировки 7 дней. Аномальное, возвращенное или скорректированное использование отменяется по исходной записи.	Doanh thu mới ở trạng thái chờ trong 7 ngày trước khi khả dụng. Lượt dùng bất thường, hoàn tiền hoặc điều chỉnh sẽ được hoàn tác theo bản ghi gốc.	新收益會先進入待釋放狀態，7 天後自動變為可用；異常、退款或沖正用量會依原記錄撤銷。	Yeni kazançlar önce serbest bırakılmayı bekler, 7 gün sonra otomatik olarak kullanılabilir olur. Olağandışı, iade edilmiş veya ters ibraz edilen kullanımlar özgün kayda göre geri alınır.
无法识别代理格式，请检查主机、端口和认证信息	Proxy format not recognized. Check the host, port, and credentials.	プロキシ形式を認識できません。ホスト、ポート、認証情報を確認してください。	Format de proxy non reconnu. Vérifiez l'hôte, le port et les identifiants.	Формат прокси не распознан. Проверьте хост, порт и учетные данные.	Không nhận diện được định dạng proxy. Hãy kiểm tra máy chủ, cổng và thông tin xác thực.	無法識別代理格式，請檢查主機、連接埠與驗證資訊	Proxy biçimi tanınamadı. Lütfen ana makineyi, bağlantı noktasını ve kimlik doğrulama bilgilerini kontrol edin.
无法读取剪贴板，请直接粘贴到主机输入框	Could not read the clipboard. Paste directly into the host field.	クリップボードを読み取れません。ホスト欄に直接貼り付けてください。	Impossible de lire le presse-papiers. Collez directement dans le champ hôte.	Не удалось прочитать буфер обмена. Вставьте значение прямо в поле хоста.	Không thể đọc bộ nhớ tạm. Hãy dán trực tiếp vào ô máy chủ.	無法讀取剪貼簿，請直接貼到主機輸入框	Pano okunamadı. Lütfen doğrudan ana makine alanına yapıştırın.
有 {{count}} 个 OAuth 账号未绑定专属代理，暂不能导入	{{count}} OAuth accounts have no dedicated proxy and cannot be imported yet	{{count}} 件の OAuth アカウントに専用プロキシがないため、まだインポートできません	{{count}} comptes OAuth n'ont pas de proxy dédié et ne peuvent pas encore être importés	У {{count}} OAuth-аккаунтов нет выделенного прокси, поэтому их пока нельзя импортировать	Có {{count}} tài khoản OAuth chưa gắn proxy riêng nên chưa thể nhập	有 {{count}} 個 OAuth 帳號未綁定專屬代理，目前無法匯入	{{count}} OAuth hesabına özel proxy bağlanmamış; henüz içe aktarılamaz.
有 {{count}} 个 OAuth 账号未绑定代理，请补充 proxy、proxy_url 或 proxy_id	{{count}} OAuth accounts have no proxy. Add proxy, proxy_url, or proxy_id.	{{count}} 件の OAuth アカウントにプロキシがありません。proxy、proxy_url、または proxy_id を追加してください。	{{count}} comptes OAuth n'ont pas de proxy. Ajoutez proxy, proxy_url ou proxy_id.	У {{count}} OAuth-аккаунтов нет прокси. Добавьте proxy, proxy_url или proxy_id.	Có {{count}} tài khoản OAuth chưa có proxy. Hãy thêm proxy, proxy_url hoặc proxy_id.	有 {{count}} 個 OAuth 帳號未綁定代理，請補上 proxy、proxy_url 或 proxy_id	{{count}} OAuth hesabına proxy bağlanmamış. proxy, proxy_url veya proxy_id ekleyin.
未知收款方式	Unknown payment method	不明な受取方法	Mode de paiement inconnu	Неизвестный способ выплаты	Phương thức nhận tiền không xác định	未知收款方式	Bilinmeyen ödeme yöntemi
正在验证账号	Verifying account	アカウントを確認中	Vérification du compte	Проверка аккаунта	Đang xác minh tài khoản	正在驗證帳號	Hesap doğrulanıyor
每个 OAuth 账号都必须配置可连通的公网代理。为提高账号存活率，建议使用静态住宅 IP。	Every OAuth account must use a reachable public proxy. A static residential IP is recommended for better account stability.	各 OAuth アカウントには接続可能な公開プロキシが必要です。安定性向上のため固定住宅 IP を推奨します。	Chaque compte OAuth doit utiliser un proxy public joignable. Une IP résidentielle statique est recommandée pour améliorer la stabilité.	Для каждого OAuth-аккаунта требуется доступный публичный прокси. Для стабильности рекомендуется статический резидентский IP.	Mỗi tài khoản OAuth phải dùng proxy công khai có thể kết nối. Nên dùng IP dân cư tĩnh để tăng độ ổn định.	每個 OAuth 帳號都必須設定可連線的公網代理。為提高帳號存活率，建議使用靜態住宅 IP。	Her OAuth hesabı için erişilebilir bir genel proxy yapılandırılmalıdır. Hesap kararlılığını artırmak için sabit bir konut IP’si kullanmanızı öneririz.
每个套餐使用自己的贡献者分成比例。OpenAI Free、Plus、Pro、Team 分别展示，互不共用。	Each plan has its own contributor revenue share. OpenAI Free, Plus, Pro, and Team are shown and configured separately.	各プランには個別の貢献者収益分配率があります。OpenAI Free、Plus、Pro、Team は別々に表示・設定されます。	Chaque offre possède sa propre part de revenus. OpenAI Free, Plus, Pro et Team sont affichés et configurés séparément.	Для каждого тарифа задается своя доля участника. OpenAI Free, Plus, Pro и Team отображаются и настраиваются отдельно.	Mỗi gói có tỷ lệ chia sẻ riêng cho người đóng góp. OpenAI Free, Plus, Pro và Team được hiển thị và cấu hình riêng.	每個套餐使用自己的貢獻者分成比例。OpenAI Free、Plus、Pro、Team 會分別顯示，互不共用。	Her plan kendi katkıda bulunan gelir paylaşımı oranını kullanır. OpenAI Free, Plus, Pro ve Team ayrı ayrı gösterilir ve oranları paylaşmaz.
每笔收益都对应一条真实用量记录，并按用量发生时生效的费率计算。	Every earning maps to a real usage record and uses the rate active when that usage occurred.	各収益は実際の利用記録に対応し、その利用時点で有効だった料率で計算されます。	Chaque gain correspond à une utilisation réelle et est calculé avec le taux en vigueur au moment de cette utilisation.	Каждая выплата соответствует реальной записи использования и рассчитывается по ставке, действовавшей в тот момент.	Mỗi khoản doanh thu tương ứng với bản ghi sử dụng thực tế và được tính theo tỷ lệ có hiệu lực tại thời điểm đó.	每筆收益都對應一筆真實用量記錄，並依用量發生時生效的費率計算。	Her kazanç, gerçek bir kullanım kaydına karşılık gelir ve kullanım anında geçerli olan ücret üzerinden hesaplanır.
添加 Anthropic、OpenAI、Gemini、Antigravity 或 Grok 账号，完成后立即贡献容量。	Add an Anthropic, OpenAI, Gemini, Antigravity, or Grok account to start contributing capacity immediately.	Anthropic、OpenAI、Gemini、Antigravity、Grok のアカウントを追加すると、すぐに容量を提供できます。	Ajoutez un compte Anthropic, OpenAI, Gemini, Antigravity ou Grok pour fournir immédiatement de la capacité.	Добавьте аккаунт Anthropic, OpenAI, Gemini, Antigravity или Grok, чтобы сразу предоставить емкость.	Thêm tài khoản Anthropic, OpenAI, Gemini, Antigravity hoặc Grok để đóng góp dung lượng ngay.	新增 Anthropic、OpenAI、Gemini、Antigravity 或 Grok 帳號，完成後即可立即貢獻容量。	Anthropic, OpenAI, Gemini, Antigravity veya Grok hesabı ekleyin; işlem tamamlanınca kapasite hemen katkıda bulunur.
添加共享账号	Add shared account	共有アカウントを追加	Ajouter un compte partagé	Добавить общий аккаунт	Thêm tài khoản dùng chung	新增共享帳號	Paylaşılan hesap ekle
添加托管账号	Add Hosted Account	ホストアカウントを追加	Ajouter un compte hébergé	Добавить размещенный аккаунт	Thêm tài khoản lưu trữ	新增托管帳號	Barındırılan hesap ekle
生成授权链接	Generate authorization link	認証リンクを生成	Générer le lien d'autorisation	Создать ссылку авторизации	Tạo liên kết ủy quyền	產生授權連結	Yetkilendirme bağlantısı oluştur
用户名（可选）	Username (optional)	ユーザー名（任意）	Nom d'utilisateur (facultatif)	Имя пользователя (необязательно)	Tên người dùng (không bắt buộc)	使用者名稱（可選）	Kullanıcı adı (isteğe bağlı)
登录您的 {{platform}} 账户并完成授权。	Sign in to your {{platform}} account and complete authorization.	{{platform}} アカウントにログインして認証を完了してください。	Connectez-vous à votre compte {{platform}} et terminez l'autorisation.	Войдите в аккаунт {{platform}} и завершите авторизацию.	Đăng nhập tài khoản {{platform}} và hoàn tất ủy quyền.	登入你的 {{platform}} 帳號並完成授權。	{{platform}} hesabınızda oturum açın ve yetkilendirmeyi tamamlayın.
确认删除这个共享账号？	Delete this shared account?	この共有アカウントを削除しますか？	Supprimer ce compte partagé ?	Удалить этот общий аккаунт?	Xóa tài khoản dùng chung này?	確定要刪除此共享帳號嗎？	Bu paylaşılan hesabı silmek istediğinizden emin misiniz?
端口	Port	ポート	Port	Порт	Cổng	連接埠	Bağlantı noktası
第 {{number}} 项：{{message}}	Item {{number}}: {{message}}	項目 {{number}}：{{message}}	Élément {{number}} : {{message}}	Элемент {{number}}: {{message}}	Mục {{number}}: {{message}}	第 {{number}} 項：{{message}}	{{number}}. öğe: {{message}}
粘贴并自动识别	Paste and detect	貼り付けて自動判定	Coller et détecter	Вставить и распознать	Dán và tự nhận diện	貼上並自動識別	Yapıştır ve otomatik algıla
累计收益	Total Earnings	累計収益	Gains cumulés	Общий доход	Tổng doanh thu	累計收益	Toplam kazanç
绑定专属代理（必填）	Bind dedicated proxy (required)	専用プロキシを設定（必須）	Associer un proxy dédié (requis)	Выделенный прокси (обязательно)	Gắn proxy riêng (bắt buộc)	綁定專屬代理（必填）	Özel proxy bağla (zorunlu)
结算	Settlement	精算	Règlement	Расчеты	Quyết toán	結算	Ödeme
缺少代理	Missing proxy	プロキシなし	Proxy manquant	Нет прокси	Thiếu proxy	缺少代理	Proxy eksik
规则与费率	Rules & Rates	規則と料率	Règles et tarifs	Правила и ставки	Quy tắc và mức phí	規則與費率	Kurallar ve ücretler
计费金额	Billed amount	課金額	Montant facturé	Сумма тарификации	Số tiền tính phí	計費金額	Faturalandırılan tutar
请先生成授权链接	Generate the authorization link first	先に認証リンクを生成してください	Générez d'abord le lien d'autorisation	Сначала создайте ссылку авторизации	Hãy tạo liên kết ủy quyền trước	請先產生授權連結	Önce yetkilendirme bağlantısını oluşturun
请先选择包含 OAuth 账号的 JSON 备份文件	Select a JSON backup containing OAuth accounts first	OAuth アカウントを含む JSON バックアップを選択してください	Sélectionnez d'abord une sauvegarde JSON contenant des comptes OAuth	Сначала выберите JSON-резервную копию с OAuth-аккаунтами	Hãy chọn tệp sao lưu JSON có tài khoản OAuth trước	請先選擇包含 OAuth 帳號的 JSON 備份檔案	Önce OAuth hesaplarını içeren bir JSON yedekleme dosyası seçin
请输入 AWS SigV4 凭证	Enter AWS SigV4 credentials	AWS SigV4 認証情報を入力してください	Saisissez les identifiants AWS SigV4	Введите учетные данные AWS SigV4	Nhập thông tin xác thực AWS SigV4	請輸入 AWS SigV4 憑證	AWS SigV4 kimlik bilgilerini girin
请输入 Service Account JSON	Enter the Service Account JSON	Service Account JSON を入力してください	Saisissez le JSON du compte de service	Введите Service Account JSON	Nhập Service Account JSON	請輸入 Service Account JSON	Service Account JSON girin
请输入授权链接或 Code	Enter the authorization link or code	認証リンクまたは Code を入力してください	Saisissez le lien d'autorisation ou le code	Введите ссылку авторизации или Code	Nhập liên kết ủy quyền hoặc Code	請輸入授權連結或 Code	Yetkilendirme bağlantısını veya Code’u girin
请输入收款账号	Enter a payment account	受取アカウントを入力してください	Saisissez un compte de paiement	Введите платежный аккаунт	Nhập tài khoản nhận tiền	請輸入收款帳號	Ödeme hesabını girin
请输入收款账号、银行卡或钱包地址	Enter a payment account, bank account, or wallet address	受取アカウント、銀行口座、またはウォレットアドレスを入力してください	Saisissez un compte de paiement, un compte bancaire ou une adresse de portefeuille	Введите платежный аккаунт, банковские реквизиты или адрес кошелька	Nhập tài khoản nhận tiền, tài khoản ngân hàng hoặc địa chỉ ví	請輸入收款帳號、銀行卡或錢包地址	Ödeme hesabını, banka hesabını veya cüzdan adresini girin
请输入有效的公网代理主机和端口	Enter a valid public proxy host and port	有効な公開プロキシのホストとポートを入力してください	Saisissez un hôte et un port de proxy public valides	Введите корректный хост и порт публичного прокси	Nhập máy chủ và cổng proxy công khai hợp lệ	請輸入有效的公網代理主機與連接埠	Geçerli bir genel proxy ana makinesi ve bağlantı noktası girin
请输入有效金额	Enter a valid amount	有効な金額を入力してください	Saisissez un montant valide	Введите корректную сумму	Nhập số tiền hợp lệ	請輸入有效金額	Geçerli bir tutar girin
请选择 JSON (.json) 文件	Select a JSON (.json) file	JSON（.json）ファイルを選択してください	Sélectionnez un fichier JSON (.json)	Выберите файл JSON (.json)	Chọn tệp JSON (.json)	請選擇 JSON (.json) 檔案	Bir JSON (.json) dosyası seçin
请选择 JSON 文件	Select a JSON file	JSON ファイルを選択してください	Sélectionnez un fichier JSON	Выберите файл JSON	Chọn tệp JSON	請選擇 JSON 檔案	Bir JSON dosyası seçin
调用后 7 天自动释放	Released automatically 7 days after usage	利用から 7 日後に自動確定	Disponible automatiquement 7 jours après l'utilisation	Автоматически становится доступно через 7 дней	Tự động phát hành sau 7 ngày sử dụng	呼叫後 7 天自動釋放	Çağrıdan 7 gün sonra otomatik olarak serbest bırakılır
调用时间	Request time	呼び出し時刻	Heure de l'appel	Время запроса	Thời gian gọi	呼叫時間	Çağrı zamanı
贡献者分成	Contributor share	貢献者分	Part du contributeur	Доля участника	Tỷ lệ người đóng góp	貢獻者分成	Katkıda bulunan payı
贡献者分成（无托管费）	Contributor share (no hosting fee)	貢献者分（ホスティング手数料なし）	Part du contributeur (sans frais d'hébergement)	Доля участника (без комиссии за размещение)	Tỷ lệ người đóng góp (không phí lưu trữ)	貢獻者分成（無托管費）	Katkıda bulunan payı (barındırma ücreti yok)
贡献订阅账号、查看收益并管理结算	Contribute subscription accounts, track earnings, and manage settlements	サブスクリプションアカウントを提供し、収益と精算を管理します	Contribuez des comptes d'abonnement, suivez les gains et gérez les règlements	Предоставляйте аккаунты подписок, отслеживайте доход и управляйте расчетами	Đóng góp tài khoản đăng ký, theo dõi doanh thu và quản lý quyết toán	貢獻訂閱帳號、查看收益並管理結算	Abonelik hesaplarıyla katkıda bulunun, kazançları görüntüleyin ve ödemeleri yönetin
账号备份文件	Account backup file	アカウントバックアップファイル	Fichier de sauvegarde des comptes	Файл резервной копии аккаунтов	Tệp sao lưu tài khoản	帳號備份檔案	Hesap yedekleme dosyası
账号备份文件解析失败	Could not parse the account backup file	アカウントバックアップファイルを解析できませんでした	Impossible d'analyser le fichier de sauvegarde des comptes	Не удалось разобрать файл резервной копии аккаунтов	Không thể phân tích tệp sao lưu tài khoản	帳號備份檔案解析失敗	Hesap yedekleme dosyası ayrıştırılamadı
账号导入并通过测试后立即进入调度，模型和销售价格会自动同步。	After an account is imported and passes testing, it enters scheduling immediately. Models and selling prices sync automatically.	アカウントはインポートとテストの完了後すぐにスケジュール対象となり、モデルと販売価格は自動同期されます。	Après importation et validation, le compte rejoint immédiatement la planification. Les modèles et prix de vente sont synchronisés automatiquement.	После импорта и проверки аккаунт сразу включается в маршрутизацию. Модели и цены продажи синхронизируются автоматически.	Sau khi nhập và vượt qua kiểm tra, tài khoản sẽ được điều phối ngay. Mô hình và giá bán tự động đồng bộ.	帳號匯入並通過測試後會立即進入調度，模型與銷售價格會自動同步。	Hesap içe aktarılıp testlerden geçtikten sonra hemen planlamaya alınır; model ve satış fiyatları otomatik eşitlenir.
账号身份	Account identity	アカウント情報	Identité du compte	Данные аккаунта	Danh tính tài khoản	帳號身分	Hesap kimliği
账号邮箱	Account email	アカウントのメールアドレス	E-mail du compte	Электронная почта аккаунта	Email tài khoản	帳號電子郵件	Hesap e-postası
账号已接入，套餐已自动识别	Account connected and plan detected	アカウントを接続し、プランを自動判定しました	Compte connecté et offre détectée automatiquement	Аккаунт подключен, тариф определен автоматически	Đã kết nối tài khoản và tự nhận diện gói	帳號已接入，套餐已自動識別	Hesap bağlandı, plan otomatik algılandı
账号自主控制	Account control	アカウントの自主管理	Contrôle du compte	Управление аккаунтом	Tự quản lý tài khoản	帳號自主控制	Hesap sahibi denetimi
平台账号 ID	Platform account ID	プラットフォームアカウント ID	ID du compte de la plateforme	ID аккаунта платформы	ID tài khoản nền tảng	平台帳號 ID	Platform hesap kimliği
托管记录 ID	Hosted record ID	ホスト記録 ID	ID de l'enregistrement hébergé	ID записи размещения	ID bản ghi lưu trữ	托管記錄 ID	Barındırma kaydı kimliği
转入余额	Transfer to balance	残高へ振替	Transférer vers le solde	Перевести на баланс	Chuyển vào số dư	轉入餘額	Bakiyeye aktar
转入失败	Transfer failed	振替に失敗しました	Échec du transfert	Ошибка перевода	Chuyển thất bại	轉入失敗	Aktarım başarısız oldu
转入平台余额	Transfer to Platform Balance	プラットフォーム残高へ振替	Transférer vers le solde de la plateforme	Перевести на баланс платформы	Chuyển vào số dư nền tảng	轉入平台餘額	Platform bakiyesine aktar
输入授权链接或 Code	Enter authorization link or code	認証リンクまたは Code を入力	Saisir le lien d'autorisation ou le code	Введите ссылку авторизации или Code	Nhập liên kết ủy quyền hoặc Code	輸入授權連結或 Code	Yetkilendirme bağlantısını veya Code’u girin
近 30 天	Last 30 Days	過去 30 日	30 derniers jours	Последние 30 дней	30 ngày gần nhất	近 30 天	Son 30 gün
还没有托管账号	No hosted accounts yet	ホストアカウントはまだありません	Aucun compte hébergé	Размещенных аккаунтов пока нет	Chưa có tài khoản lưu trữ	尚無托管帳號	Henüz barındırılan hesap yok
进入调度	Scheduling	スケジュール対象	Planification	Маршрутизация	Đưa vào điều phối	進入調度	Planlamaya al
选择平台	Select platform	プラットフォームを選択	Sélectionner la plateforme	Выберите платформу	Chọn nền tảng	選擇平台	Platform seçin
选择平台和账号类型后授权，系统会自动识别套餐并归入对应共享池。	Select a platform and account type, then authorize it. The system detects the plan and assigns it to the matching shared pool.	プラットフォームとアカウント種別を選んで認証すると、システムがプランを判定し、対応する共有プールに割り当てます。	Sélectionnez une plateforme et un type de compte, puis autorisez-le. Le système détecte l'offre et l'affecte au pool partagé correspondant.	Выберите платформу и тип аккаунта, затем выполните авторизацию. Система определит тариф и добавит аккаунт в соответствующий общий пул.	Chọn nền tảng và loại tài khoản rồi ủy quyền. Hệ thống sẽ nhận diện gói và đưa vào nhóm dùng chung tương ứng.	選擇平台與帳號類型後進行授權，系統會自動識別套餐並歸入對應的共享池。	Bir platform ve hesap türü seçip yetkilendirme yapın. Sistem planı otomatik algılar ve ilgili paylaşılan havuza ekler.
选择文件	Choose file	ファイルを選択	Choisir un fichier	Выбрать файл	Chọn tệp	選擇檔案	Dosya seçin
释放状态	Release status	確定状態	État de libération	Статус разблокировки	Trạng thái phát hành	釋放狀態	Serbest bırakma durumu
金额超过可用收益	Amount exceeds available earnings	金額が利用可能な収益を超えています	Le montant dépasse les gains disponibles	Сумма превышает доступный доход	Số tiền vượt quá doanh thu khả dụng	金額超過可用收益	Tutar kullanılabilir kazancı aşıyor
隔离中	Quarantined	隔離中	En quarantaine	В карантине	Đang cách ly	隔離中	Karantinada

`.trim();

const sharedSubscriptionTranslations = Object.fromEntries(
  ['zh', ...translatedLocales, 'es', 'pt-BR', 'de', 'ar', 'id', 'ko'].map(
    (locale) => [locale, {}],
  ),
);

for (const line of translationRows.split('\n')) {
  const [key, ...values] = line.split('\t');
  if (!key || values.length !== translatedLocales.length) {
    throw new Error(`Invalid shared subscription translation row: ${line}`);
  }
  sharedSubscriptionTranslations.zh[key] = key;
  translatedLocales.forEach((locale, index) => {
    sharedSubscriptionTranslations[locale][key] = values[index];
  });
}

// These locales are newly available in the main UI. Their dedicated locale
// files provide the general interface strings, while the shared-subscription
// catalog safely falls back to English until its long-form glossary is
// translated. Keeping the complete key set here prevents the page from
// displaying raw Chinese message IDs.
for (const locale of ['es', 'pt-BR', 'de', 'ar', 'id', 'ko']) {
  sharedSubscriptionTranslations[locale] = {
    ...sharedSubscriptionTranslations.en,
  };
}

export default sharedSubscriptionTranslations;
